function phcltsenset(varargin);
% phcltsenset( [...] );
% T Sense T
h = timeplot({'TS0_T','TS1_T','TS2_T','TS3_T','TS4_T','TS5_T'}, ...
      'T Sense T', ...
      'T', ...
      {'TS0\_T','TS1\_T','TS2\_T','TS3\_T','TS4\_T','TS5\_T'}, ...
      varargin{:} );
