function phclqclistatmode(varargin);
% phclqclistatmode( [...] );
% QCL Istat mode
h = timeplot({'QCLI_mode'}, ...
      'QCL Istat mode', ...
      'mode', ...
      {'QCLI\_mode'}, ...
      varargin{:} );
