function phclic(varargin);
% phclic( [...] );
% Inlet Control
h = timeplot({'IHeatBlkTSt','IHeatBlkCT'}, ...
      'Inlet Control', ...
      'Control', ...
      {'IHeatBlkTSt','IHeatBlkCT'}, ...
      varargin{:} );
