function phclctc(varargin);
% phclctc( [...] );
% Cell T Control
h = timeplot({'ICelTSt','ICelCT'}, ...
      'Cell T Control', ...
      'T Control', ...
      {'ICelTSt','ICelCT'}, ...
      varargin{:} );
