function phcldpvtc(varargin);
% phcldpvtc( [...] );
% DPV T Control
h = timeplot({'IDPVCT','IDPVTSt'}, ...
      'DPV T Control', ...
      'T Control', ...
      {'IDPVCT','IDPVTSt'}, ...
      varargin{:} );
