function phclqclistaterr(varargin);
% phclqclistaterr( [...] );
% QCL Istat err
h = timeplot({'QCLI_err'}, ...
      'QCL Istat err', ...
      'err', ...
      {'QCLI\_err'}, ...
      varargin{:} );
