function phclqclistatfifodep(varargin);
% phclqclistatfifodep( [...] );
% QCL Istat fifodep
h = timeplot({'QCLI_fifodep'}, ...
      'QCL Istat fifodep', ...
      'fifodep', ...
      {'QCLI\_fifodep'}, ...
      varargin{:} );
