function phcltssp(varargin);
% phcltssp( [...] );
% Temps SSP
h = timeplot({'SSP_T_FPGA','SSP_T_HtSink','ISSPT','IPampT'}, ...
      'Temps SSP', ...
      'SSP', ...
      {'SSP\_T\_FPGA','SSP\_T\_HtSink','ISSPT','IPampT'}, ...
      varargin{:} );
