function phclqclistats(varargin);
% phclqclistats( [...] );
% QCL Istat Stale
h = timeplot({'QCLI_Stale','SSP_Stale'}, ...
      'QCL Istat Stale', ...
      'Stale', ...
      {'QCLI\_Stale','SSP\_Stale'}, ...
      varargin{:} );
