function phclqclistatflash(varargin);
% phclqclistatflash( [...] );
% QCL Istat flash
h = timeplot({'QCLI_flash'}, ...
      'QCL Istat flash', ...
      'flash', ...
      {'QCLI\_flash'}, ...
      varargin{:} );
