function phcltr(varargin);
% phcltr( [...] );
% Temps Rover
h = timeplot({'IRv1T','IRv2T','IRv3T','IRv4T','IRv5T'}, ...
      'Temps Rover', ...
      'Rover', ...
      {'IRv1T','IRv2T','IRv3T','IRv4T','IRv5T'}, ...
      varargin{:} );
