function phcldacst(varargin);
% phcldacst( [...] );
% DACS T
h = timeplot({'vl_bdT','vl_cpuT','DACS_T1C','DACS_T2C'}, ...
      'DACS T', ...
      'T', ...
      {'vl\_bdT','vl\_cpuT','DACS\_T1C','DACS\_T2C'}, ...
      varargin{:} );
