function phclhks(varargin);
% phclhks( [...] );
% HK Spare
h = timeplot({'Sp6AI','Sp7AI','Sp8AI','SpAI9'}, ...
      'HK Spare', ...
      'Spare', ...
      {'Sp6AI','Sp7AI','Sp8AI','SpAI9'}, ...
      varargin{:} );
